[package]
name = "mycli"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.6.2"
aws-sdk-organizations = "1.75.0"
aws-sdk-s3 = "1.85.0"
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
tokio = { version = "1.45.0", features = ["full"] }
